---
- name: install postfix
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - postfix
    - mailx

- name: Start and enable postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Configure postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: reload postfix
