---
- hosts: "{{hosts}}"
  become: true

  roles:
    - role: dns
      tags:
        - dns
    - role: hostfix
      tags:
        - hostfix
    - role: subscribe
      tags:
        - subscribe
    - role: packages
      tags:
        - packages
    - role: selinux
      tags:
        - selinux
    - role: firewall
      tags:
        - firewall
    - role: ntp
      tags:
        - ntp
    - role: sendmail
      tags:
        - sendmail
    - role: postfix
      tags:
        - postfix
    - role: sysctl
      tags:
        - sysctl
    - role: cron
      tags:
        - cron
